// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { resolveSupabaseAnonKey, resolveSupabaseUrl } from "./resolve-env";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const url = resolveSupabaseUrl();
const key = resolveSupabaseAnonKey();

export const supabase = createClient<Database>(url, key, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
